# Generated by Django 3.1.6 on 2021-02-12 00:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0009_auto_20210211_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='creator',
        ),
        migrations.AddField(
            model_name='friendship',
            name='creator',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='friend',
        ),
        migrations.AddField(
            model_name='friendship',
            name='friend',
            field=models.ManyToManyField(related_name='friend', to=settings.AUTH_USER_MODEL),
        ),
    ]
